// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "dt",
        "main",
        "weather",
        "clouds",
        "wind",
        "visibility",
        "pop",
        "rain",
        "snow",
        "sys",
        "dt_txt"
})
public class List {

  @JsonProperty("dt")
  private int dt;
  @JsonProperty("main")
  private Main main;
  @JsonProperty("weather")
  private java.util.List<WeatherData> weather = null;
  @JsonProperty("clouds")
  private Clouds clouds;
  @JsonProperty("wind")
  private Wind wind;
  @JsonProperty("visibility")
  private int visibility;
  @JsonProperty("pop")
  private double pop;
  @JsonProperty("rain")
  private Rain rain;
  @JsonProperty("snow")
  private Snow snow;
  @JsonProperty("sys")
  private Sys sys;
  @JsonProperty("dt_txt")
  private String dtTxt;

  /**
   * No args constructor for use in serialization
   *
   */
  public List() {
  }

  /**
   *
   * @param dt
   * @param weather
   * @param main
   * @param clouds
   * @param wind
   * @param visibility
   * @param pop
   * @param rain
   * @param snow
   * @param sys
   * @param dtTxt
   */
  public List(int dt, Main main, java.util.List<WeatherData> weather, Clouds clouds, Wind wind, int visibility, double pop, Rain rain, Snow snow, Sys sys, String dtTxt) {
    super();
    this.dt = dt;
    this.main = main;
    this.weather = weather;
    this.clouds = clouds;
    this.wind = wind;
    this.visibility = visibility;
    this.pop = pop;
    this.rain = rain;
    this.snow = snow;
    this.sys = sys;
    this.dtTxt = dtTxt;
  }

  @JsonProperty("dt")
  public int getDt() {
    return dt;
  }

  @JsonProperty("dt")
  public void setDt(int dt) {
    this.dt = dt;
  }

  @JsonProperty("main")
  public Main getMain() {
    return main;
  }

  @JsonProperty("main")
  public void setMain(Main main) {
    this.main = main;
  }

  @JsonProperty("weather")
  public java.util.List<WeatherData> getWeather() {
    return weather;
  }

  @JsonProperty("weather")
  public void setWeather(java.util.List<WeatherData> weather) {
    this.weather = weather;
  }

  @JsonProperty("clouds")
  public Clouds getClouds() {
    return clouds;
  }

  @JsonProperty("clouds")
  public void setClouds(Clouds clouds) {
    this.clouds = clouds;
  }

  @JsonProperty("wind")
  public Wind getWind() {
    return wind;
  }

  @JsonProperty("wind")
  public void setWind(Wind wind) {
    this.wind = wind;
  }

  @JsonProperty("visibility")
  public int getVisibility() {
    return visibility;
  }

  @JsonProperty("visibility")
  public void setVisibility(int visibility) {
    this.visibility = visibility;
  }

  @JsonProperty("pop")
  public double getPop() {
    return pop;
  }

  @JsonProperty("pop")
  public void setPop(double pop) {
    this.pop = pop;
  }

  @JsonProperty("rain")
  public Rain getRain() {
    return rain;
  }

  @JsonProperty("rain")
  public void setRain(Rain rain) {
    this.rain = rain;
  }

  @JsonProperty("snow")
  public Snow getSnow() {
    return snow;
  }

  @JsonProperty("snow")
  public void setSnow(Snow snow) {
    this.snow = snow;
  }

  @JsonProperty("sys")
  public Sys getSys() {
    return sys;
  }

  @JsonProperty("sys")
  public void setSys(Sys sys) {
    this.sys = sys;
  }

  @JsonProperty("dt_txt")
  public String getDtTxt() {
    return dtTxt;
  }

  @JsonProperty("dt_txt")
  public void setDtTxt(String dtTxt) {
    this.dtTxt = dtTxt;
  }

}
