// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "temp",
        "feels_like",
        "temp_min",
        "temp_max",
        "pressure",
        "sea_level",
        "grnd_level",
        "humidity",
        "temp_kf"
})
public class Main {

  @JsonProperty("temp")
  private double temp;
  @JsonProperty("feels_like")
  private double feelsLike;
  @JsonProperty("temp_min")
  private double tempMin;
  @JsonProperty("temp_max")
  private double tempMax;
  @JsonProperty("pressure")
  private int pressure;
  @JsonProperty("sea_level")
  private int seaLevel;
  @JsonProperty("grnd_level")
  private int grndLevel;
  @JsonProperty("humidity")
  private int humidity;
  @JsonProperty("temp_kf")
  private double tempKf;

  /**
   * No args constructor for use in serialization
   *
   */
  public Main() {
  }

  /**
   *
   * @param feelsLike
   * @param tempMax
   * @param temp
   * @param seaLevel
   * @param humidity
   * @param pressure
   * @param tempKf
   * @param grndLevel
   * @param tempMin
   */
  public Main(double temp, double feelsLike, double tempMin, double tempMax, int pressure, int seaLevel, int grndLevel, int humidity, int tempKf) {
    super();
    this.temp = temp;
    this.feelsLike = feelsLike;
    this.tempMin = tempMin;
    this.tempMax = tempMax;
    this.pressure = pressure;
    this.seaLevel = seaLevel;
    this.grndLevel = grndLevel;
    this.humidity = humidity;
    this.tempKf = tempKf;
  }

  @JsonProperty("temp")
  public double getTemp() {
    return temp;
  }

  @JsonProperty("temp")
  public void setTemp(double temp) {
    this.temp = temp;
  }

  @JsonProperty("feels_like")
  public double getFeelsLike() {
    return feelsLike;
  }

  @JsonProperty("feels_like")
  public void setFeelsLike(double feelsLike) {
    this.feelsLike = feelsLike;
  }

  @JsonProperty("temp_min")
  public double getTempMin() {
    return tempMin;
  }

  @JsonProperty("temp_min")
  public void setTempMin(double tempMin) {
    this.tempMin = tempMin;
  }

  @JsonProperty("temp_max")
  public double getTempMax() {
    return tempMax;
  }

  @JsonProperty("temp_max")
  public void setTempMax(double tempMax) {
    this.tempMax = tempMax;
  }

  @JsonProperty("pressure")
  public int getPressure() {
    return pressure;
  }

  @JsonProperty("pressure")
  public void setPressure(int pressure) {
    this.pressure = pressure;
  }

  @JsonProperty("sea_level")
  public int getSeaLevel() {
    return seaLevel;
  }

  @JsonProperty("sea_level")
  public void setSeaLevel(int seaLevel) {
    this.seaLevel = seaLevel;
  }

  @JsonProperty("grnd_level")
  public int getGrndLevel() {
    return grndLevel;
  }

  @JsonProperty("grnd_level")
  public void setGrndLevel(int grndLevel) {
    this.grndLevel = grndLevel;
  }

  @JsonProperty("humidity")
  public int getHumidity() {
    return humidity;
  }

  @JsonProperty("humidity")
  public void setHumidity(int humidity) {
    this.humidity = humidity;
  }

  @JsonProperty("temp_kf")
  public double getTempKf() {
    return tempKf;
  }

  @JsonProperty("temp_kf")
  public void setTempKf(double tempKf) {
    this.tempKf = tempKf;
  }

}
