// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "id",
        "main",
        "description",
        "icon"
})
public class WeatherData {

  @JsonProperty("id")
  private int id;
  @JsonProperty("main")
  private String main;
  @JsonProperty("description")
  private String description;
  @JsonProperty("icon")
  private String icon;

  /**
   * No args constructor for use in serialization
   *
   */
  public WeatherData() {
  }

  /**
   *
   * @param icon
   * @param description
   * @param main
   * @param id
   */
  public WeatherData(int id, String main, String description, String icon) {
    super();
    this.id = id;
    this.main = main;
    this.description = description;
    this.icon = icon;
  }

  @JsonProperty("id")
  public int getId() {
    return id;
  }

  @JsonProperty("id")
  public void setId(int id) {
    this.id = id;
  }

  @JsonProperty("main")
  public String getMain() {
    return main;
  }

  @JsonProperty("main")
  public void setMain(String main) {
    this.main = main;
  }

  @JsonProperty("description")
  public String getDescription() {
    return description;
  }

  @JsonProperty("description")
  public void setDescription(String description) {
    this.description = description;
  }

  @JsonProperty("icon")
  public String getIcon() {
    return icon;
  }

  @JsonProperty("icon")
  public void setIcon(String icon) {
    this.icon = icon;
  }

}
