// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "cod",
        "message",
        "cnt",
        "list",
        "city"
})
public class Weather {

    @JsonProperty("cod")
    private String cod;
    @JsonProperty("message")
    private int message;
    @JsonProperty("cnt")
    private int cnt;
    @JsonProperty("list")
    private List[] list = null;
    @JsonProperty("city")
    private City city;

    /**
     * No args constructor for use in serialization
     *
     */
    public Weather() {
    }

    /**
     *
     * @param city
     * @param cnt
     * @param cod
     * @param message
     * @param list
     */
    public Weather(String cod, int message, int cnt, List[] list, City city) {
        super();
        this.cod = cod;
        this.message = message;
        this.cnt = cnt;
        this.list = list;
        this.city = city;
    }

    @JsonProperty("cod")
    public String getCod() {
        return cod;
    }

    @JsonProperty("cod")
    public void setCod(String cod) {
        this.cod = cod;
    }

    @JsonProperty("message")
    public int getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(int message) {
        this.message = message;
    }

    @JsonProperty("cnt")
    public int getCnt() {
        return cnt;
    }

    @JsonProperty("cnt")
    public void setCnt(int cnt) {
        this.cnt = cnt;
    }

    @JsonProperty("list")
    public List[] getList() {
        return list;
    }

    @JsonProperty("list")
    public void setList(List[] list) {
        this.list = list;
    }

    @JsonProperty("city")
    public City getCity() {
        return city;
    }

    @JsonProperty("city")
    public void setCity(City city) {
        this.city = city;
    }

}
