// Generated by http://www.jsonschema2pojo.org

package de.hdm_stuttgart.mi.sd1.weather.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "speed",
        "deg",
        "gust"
})
public class Wind {

  @JsonProperty("speed")
  private double speed;
  @JsonProperty("deg")
  private int deg;
  @JsonProperty("gust")
  private double gust;

  /**
   * No args constructor for use in serialization
   *
   */
  public Wind() {
  }

  /**
   *
   * @param deg
   * @param speed
   */
  public Wind(double speed, int deg) {
    super();
    this.speed = speed;
    this.deg = deg;
  }

  @JsonProperty("speed")
  public double getSpeed() {
    return speed;
  }

  @JsonProperty("speed")
  public void setSpeed(double speed) {
    this.speed = speed;
  }

  @JsonProperty("deg")
  public int getDeg() {
    return deg;
  }

  @JsonProperty("deg")
  public void setDeg(int deg) {
    this.deg = deg;
  }

  @JsonProperty("gust")
  public double getGust() {
    return gust;
  }

  @JsonProperty("gust")
  public void setGust(double gust) {
    this.gust = gust;
  }
}
